serviceMaps:
  serviceName: pgr-services
  mappings:
    - version: 1.0
      description: Persists pgr service request in tables
      fromTopic: save-pgr-request-audit
      isTransaction: true
      isAuditEnabled: true
      module: PGR
      objecIdJsonPath: $.id
      tenantIdJsonPath: $.tenantId
      transactionCodeJsonPath: $.transactionCode
      auditAttributeBasePath: $.service

      queryMaps:

        - query: INSERT INTO eg_pgr_service_v2(id, tenantid, servicecode, servicerequestid, description, accountid, additionaldetails, applicationstatus, source, createdby, createdtime, lastmodifiedby, lastmodifiedtime) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
          basePath: $.service
          jsonMaps:
            - jsonPath: $.service.id

            - jsonPath: $.service.tenantId

            - jsonPath: $.service.serviceCode

            - jsonPath: $.service.serviceRequestId

            - jsonPath: $.service.description

            - jsonPath: $.service.accountId

            - jsonPath: $.service.additionalDetail
              type: JSON
              dbType: JSONB

            - jsonPath: $.service.applicationStatus

            - jsonPath: $.service.source

            - jsonPath: $.service.auditDetails.createdBy

            - jsonPath: $.service.auditDetails.createdTime

            - jsonPath: $.service.auditDetails.lastModifiedBy

            - jsonPath: $.service.auditDetails.lastModifiedTime

        - query: INSERT INTO eg_pgr_address_v2(id, tenantid, parentid, doorno, plotno, buildingname, street, landmark, city, pincode, locality, district, region, state, country, latitude, longitude, additionaldetails, createdby, createdtime, lastmodifiedby, lastmodifiedtime) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
          basePath: $.service.address
          jsonMaps:
            - jsonPath: $.service.address.id

            - jsonPath: $.service.address.tenantId

            - jsonPath: $.service.id

            - jsonPath: $.service.address.doorNo

            - jsonPath: $.service.address.plotNo

            - jsonPath: $.service.address.buildingName

            - jsonPath: $.service.address.street

            - jsonPath: $.service.address.landmark

            - jsonPath: $.service.address.city

            - jsonPath: $.service.address.pincode

            - jsonPath: $.service.address.locality.code

            - jsonPath: $.service.address.district

            - jsonPath: $.service.address.region

            - jsonPath: $.service.address.state

            - jsonPath: $.service.address.country

            - jsonPath: $.service.address.geoLocation.latitude

            - jsonPath: $.service.address.geoLocation.longitude

            - jsonPath: $.service.address.additionDetails
              type: JSON
              dbType: JSONB

            - jsonPath: $.service.auditDetails.createdBy

            - jsonPath: $.service.auditDetails.createdTime

            - jsonPath: $.service.auditDetails.lastModifiedBy

            - jsonPath: $.service.auditDetails.lastModifiedTime



    - version: 1.0
      description: Updates pgr service request in tables
      fromTopic: update-pgr-request
      isTransaction: true
      queryMaps:

        - query: UPDATE eg_pgr_service_v2 SET servicecode=?, rating = ?,servicerequestid=?, description=?, accountid=?, additionaldetails=?, applicationstatus=?, lastmodifiedby=?, lastmodifiedtime=? WHERE id=?;
          basePath: service
          jsonMaps:
            - jsonPath: $.service.serviceCode

            - jsonPath: $.service.rating

            - jsonPath: $.service.serviceRequestId

            - jsonPath: $.service.description

            - jsonPath: $.service.accountId

            - jsonPath: $.service.additionalDetail
              type: JSON
              dbType: JSONB

            - jsonPath: $.service.applicationStatus

            - jsonPath: $.service.auditDetails.lastModifiedBy

            - jsonPath: $.service.auditDetails.lastModifiedTime

            - jsonPath: $.service.id


        - query: UPDATE eg_pgr_address_v2 SET doorno=?, plotno=?, buildingname=?, street=?, landmark=?, city=?, pincode=?, locality=?, district=?, region=?, state=?, country=?, latitude=?, longitude=?,additionaldetails=?, lastmodifiedby=?, lastmodifiedtime=? WHERE id=?;
          basePath: service.address
          jsonMaps:

            - jsonPath: $.service.address.doorNo

            - jsonPath: $.service.address.plotNo

            - jsonPath: $.service.address.buildingName

            - jsonPath: $.service.address.street

            - jsonPath: $.service.address.landmark

            - jsonPath: $.service.address.city

            - jsonPath: $.service.address.pincode

            - jsonPath: $.service.address.locality.code

            - jsonPath: $.service.address.district

            - jsonPath: $.service.address.region

            - jsonPath: $.service.address.state

            - jsonPath: $.service.address.country

            - jsonPath: $.service.address.geoLocation.latitude

            - jsonPath: $.service.address.geoLocation.longitude

            - jsonPath: $.service.address.additionDetails
              type: JSON
              dbType: JSONB

            - jsonPath: $.service.auditDetails.lastModifiedBy

            - jsonPath: $.service.auditDetails.lastModifiedTime

            - jsonPath: $.service.address.id


    - version: 1.0
      description: Updates pgr status for auto escalate
      fromTopic: pgr-auto-escalation
      isTransaction: true
      queryMaps:

        - query: UPDATE eg_pgr_service_v2 SET applicationstatus=?, lastmodifiedby=?, lastmodifiedtime=? WHERE serviceRequestId=? AND tenantId=?;
          basePath: ProcessInstances.*
          jsonMaps:
            - jsonPath: $.ProcessInstances.*.state.applicationStatus

            - jsonPath: $.ProcessInstances.*.auditDetails.lastModifiedBy

            - jsonPath: $.ProcessInstances.*.auditDetails.lastModifiedTime

            - jsonPath: $.ProcessInstances.*.businessId

            - jsonPath: $.ProcessInstances.*.tenantId