serviceMaps:
  serviceName: property-services
  mappings:
  - version: 1.0
    description: Persists assessment details to eg_pt_assessment table
    fromTopic: save-pt-assessment
    isTransaction: true
    queryMaps:

    - query: INSERT INTO eg_pt_assessment (id, financialyear, tenantid, assessmentNumber, status, propertyId, source, assessmentDate, buildUpArea, additionaldetails, createdby, lastmodifiedby, createdtime, lastmodifiedtime) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
      basePath: Assessment
      jsonMaps:

      - jsonPath: $.Assessment.id

      - jsonPath: $.Assessment.financialYear

      - jsonPath: $.Assessment.tenantId

      - jsonPath: $.Assessment.assessmentNumber

      - jsonPath: $.Assessment.status

      - jsonPath: $.Assessment.propertyID

      - jsonPath: $.Assessment.source

      - jsonPath: $.Assessment.assessmentDate

      - jsonPath: $.Assessment.buildUpArea

      - jsonPath: $.Assessment.additionalDetails
        type: JSON
        dbType: JSONB

      - jsonPath: $.Assessment.auditDetails.createdBy

      - jsonPath: $.Assessment.auditDetails.lastModifiedBy

      - jsonPath: $.Assessment.auditDetails.createdTime

      - jsonPath: $.Assessment.auditDetails.lastModifiedTime



    - query: INSERT INTO eg_pt_unit (tenantid, id, assessmentId, floorNo, unitArea, usageCategory, occupancyType, occupancyDate, constructionType, arv, active, createdby, createdtime, lastmodifiedby, lastmodifiedtime) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
      basePath: Assessment.units.*
      jsonMaps:

      - jsonPath: $.Assessment.units.*.tenantId

      - jsonPath: $.Assessment.units.*.id

      - jsonPath: $.Assessment.units.*.assessmentId

      - jsonPath: $.Assessment.units.*.floorNo

      - jsonPath: $.Assessment.units.*.unitArea

      - jsonPath: $.Assessment.units.*.usageCategory

      - jsonPath: $.Assessment.units.*.occupancyType

      - jsonPath: $.Assessment.units.*.occupancyDate

      - jsonPath: $.Assessment.units.*.constructionType

      - jsonPath: $.Assessment.units.*.active

      - jsonPath: $.Assessment.units.*.arv

      - jsonPath: $.Assessment.units.*.auditDetails.createdBy

      - jsonPath: $.Assessment.units.*.auditDetails.createdTime

      - jsonPath: $.Assessment.units.*.auditDetails.lastModifiedBy

      - jsonPath: $.Assessment.units.*.auditDetails.lastModifiedTime



    - query: INSERT INTO eg_pt_document (id, tenantid, entityid, documenttype, filestore, documentuid, status, createdby, lastmodifiedby, createdtime, lastmodifiedtime) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?);
      basePath: $.Assessment.documents.*
      jsonMaps:

      - jsonPath: $.Assessment.documents.*.id

      - jsonPath: $.Assessment.documents.*.tenantId

      - jsonPath: $.Assessment.id

      - jsonPath: $.Assessment.documents.*.documentType

      - jsonPath: $.Assessment.documents.*.fileStore

      - jsonPath: $.Assessment.documents.*.documentUid

      - jsonPath: $.Assessment.documents.*.status

      - jsonPath: $.Assessment.documents.*.auditDetails.createdBy

      - jsonPath: $.Assessment.documents.*.auditDetails.lastModifiedBy

      - jsonPath: $.Assessment.documents.*.auditDetails.createdTime

      - jsonPath: $.Assessment.documents.*.auditDetails.lastModifiedTime
      
      
      
  - version: 1.0
    description: Updates assessment details to eg_pt_assessment table
    fromTopic: update-pt-assessment
    isTransaction: true
    queryMaps:
    
    - query: INSERT INTO eg_pt_assessment_audit SELECT *, (SELECT extract(epoch from now())) FROM eg_pt_assessment WHERE id = ?;
      basePath: Assessment
      jsonMaps:

      - jsonPath: $.Assessment.id
      
      
    - query: INSERT INTO eg_pt_unit_audit SELECT *, (SELECT extract(epoch from now())) FROM eg_pt_unit WHERE id = ?;
      basePath: Assessment.units.*
      jsonMaps:

      - jsonPath: $.Assessment.units.*.id
      

    - query: UPDATE eg_pt_assessment SET financialyear = ?, status = ?, source = ?, assessmentDate = ?, buildUpArea = ?, additionaldetails = ?, lastmodifiedby = ?, lastmodifiedtime = ? WHERE id = ?;
      basePath: Assessment
      jsonMaps:

      - jsonPath: $.Assessment.financialYear

      - jsonPath: $.Assessment.status

      - jsonPath: $.Assessment.source

      - jsonPath: $.Assessment.assessmentDate

      - jsonPath: $.Assessment.buildUpArea

      - jsonPath: $.Assessment.additionalDetails
        type: JSON
        dbType: JSONB

      - jsonPath: $.Assessment.auditDetails.lastModifiedBy

      - jsonPath: $.Assessment.auditDetails.lastModifiedTime
      
      - jsonPath: $.Assessment.id




    - query: INSERT INTO eg_pt_unit (tenantid, id, assessmentId, floorNo, unitArea, usageCategory, occupancyType, occupancyDate, constructionType, arv, active, createdby, createdtime, lastmodifiedby, lastmodifiedtime) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?) ON CONFLICT (id) DO UPDATE floorNo = ?, unitArea = ?, usageCategory = ?, occupancyType = ?, occupancyDate = ?, constructionType = ?, arv = ?, active = ?, lastmodifiedby = ?, lastmodifiedtime = ?;
      basePath: Assessment.units.*
      jsonMaps:

      - jsonPath: $.Assessment.units.*.tenantId

      - jsonPath: $.Assessment.units.*.id

      - jsonPath: $.Assessment.units.*.assessmentId

      - jsonPath: $.Assessment.units.*.floorNo

      - jsonPath: $.Assessment.units.*.unitArea

      - jsonPath: $.Assessment.units.*.usageCategory

      - jsonPath: $.Assessment.units.*.occupancyType

      - jsonPath: $.Assessment.units.*.occupancyDate

      - jsonPath: $.Assessment.units.*.constructionType

      - jsonPath: $.Assessment.units.*.active

      - jsonPath: $.Assessment.units.*.arv

      - jsonPath: $.Assessment.units.*.auditDetails.createdBy

      - jsonPath: $.Assessment.units.*.auditDetails.createdTime

      - jsonPath: $.Assessment.units.*.auditDetails.lastModifiedBy

      - jsonPath: $.Assessment.units.*.auditDetails.lastModifiedTime
      
      - jsonPath: $.Assessment.units.*.floorNo

      - jsonPath: $.Assessment.units.*.unitArea

      - jsonPath: $.Assessment.units.*.usageCategory

      - jsonPath: $.Assessment.units.*.occupancyType

      - jsonPath: $.Assessment.units.*.occupancyDate

      - jsonPath: $.Assessment.units.*.constructionType

      - jsonPath: $.Assessment.units.*.active

      - jsonPath: $.Assessment.units.*.arv

      - jsonPath: $.Assessment.units.*.auditDetails.lastModifiedBy

      - jsonPath: $.Assessment.units.*.auditDetails.lastModifiedTime




    - query: INSERT INTO eg_pt_document (id, tenantid, entityid, documenttype, filestore, documentuid, status, createdby, lastmodifiedby, createdtime, lastmodifiedtime) VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?) ON CONFLICT (id) DO UPDATE documenttype = ?, documentuid = ?, status = ?, lastmodifiedby = ?, lastmodifiedtime = ?;
      basePath: $.Assessment.documents.*
      jsonMaps:

      - jsonPath: $.Assessment.documents.*.id

      - jsonPath: $.Assessment.documents.*.tenantId

      - jsonPath: $.Assessment.id

      - jsonPath: $.Assessment.documents.*.documentType

      - jsonPath: $.Assessment.documents.*.fileStore

      - jsonPath: $.Assessment.documents.*.documentUid

      - jsonPath: $.Assessment.documents.*.status

      - jsonPath: $.Assessment.documents.*.auditDetails.createdBy

      - jsonPath: $.Assessment.documents.*.auditDetails.lastModifiedBy

      - jsonPath: $.Assessment.documents.*.auditDetails.createdTime

      - jsonPath: $.Assessment.documents.*.auditDetails.lastModifiedTime
      
      - jsonPath: $.Assessment.documents.*.documentType

      - jsonPath: $.Assessment.documents.*.documentUid

      - jsonPath: $.Assessment.documents.*.status

      - jsonPath: $.Assessment.documents.*.auditDetails.lastModifiedBy

      - jsonPath: $.Assessment.documents.*.auditDetails.lastModifiedTime
      
      
      
      