SearchDefinitions:
 moduleName: bill-genie
 summary: Search configs for bill-genie
 version: 1.0.0
 definitions:
 - name: billswithaddranduser
   isCustomerRowMapEnabled: true
   rowMapperKey: billsearch
   query: 
    baseQuery:   with bill_data as ( 

            SELECT b.id AS b_id, b.mobilenumber, 
            b.tenantid AS b_tenantid, b.payername AS b_payername, 
            b.payeraddress AS b_payeraddress, b.payeremail AS b_payeremail, 
            b.isactive AS b_isactive, b.iscancelled AS b_iscancelled, 
            b.createdby AS b_createdby, b.status as b_status,b.filestoreid AS b_filestoreid,
            b.createddate AS b_createddate, b.lastmodifiedby AS b_lastmodifiedby, 
            b.lastmodifieddate AS b_lastmodifieddate, bd.id AS bd_id, 
            bd.billid AS bd_billid, bd.tenantid AS bd_tenantid,
            bd.businessservice AS bd_businessservice, bd.demandid, 
            bd.fromperiod, bd.toperiod, 
            bd.billno AS bd_billno, bd.billdate AS bd_billdate, 
            bd.consumercode AS bd_consumercode, bd.consumertype AS bd_consumertype, 
            bd.billdescription AS bd_billdescription, bd.displaymessage AS bd_displaymessage, 
            bd.minimumamount AS bd_minimumamount, bd.totalamount AS bd_totalamount, 
            bd.callbackforapportioning AS bd_callbackforapportioning, bd.expirydate AS bd_expirydate, 
            bd.partpaymentallowed AS bd_partpaymentallowed, bd.isadvanceallowed as bd_isadvanceallowed, 
            bd.collectionmodesnotallowed AS bd_collectionmodesnotallowed, bd.createddate as bd_createddate, 
            b.additionaldetails as b_additionaldetails,  bd.additionaldetails as bd_additionaldetails,
            ad.id AS ad_id, ad.tenantid AS ad_tenantid, 
            ad.billdetail AS ad_billdetail, ad.glcode AS ad_glcode, 
            ad.orderno AS ad_orderno, ad.accountdescription AS ad_accountdescription, 
            ad.amount AS ad_amount, ad.adjustedamount AS ad_adjustedamount, 
            ad.taxheadcode AS ad_taxheadcode, ad.demanddetailid, 
            ad.isactualdemand AS ad_isactualdemand, ad.purpose AS ad_purpose,   
            ad.additionaldetails as ad_additionaldetails,
            ptadd.doorNo as ptadd_doorNo,ptadd.landmark as ptadd_landmark, 
            ptadd.city as ptadd_city, ptadd.pincode as ptadd_pincode, 
            ptadd.locality as ptadd_locality, ptown.userid as ptown_userid 
            
            FROM egbs_bill_v1 b INNER JOIN egbs_billdetail_v1 bd ON b.id = bd.billid AND b.tenantid = bd.tenantid 
            INNER JOIN egbs_billaccountdetail_v1 ad ON bd.id = ad.billdetail AND bd.tenantid = ad.tenantid 
            LEFT OUTER JOIN eg_pt_property pt ON bd.consumercode = pt.propertyid 
            INNER JOIN eg_pt_address ptadd ON ptadd.propertyid = pt.id
            INNER JOIN eg_pt_asmt_assessment ptdet ON ptdet.propertyid = pt.propertyid 
            INNER JOIN eg_pt_owner ptown ON pt.id = ptown.propertyid $where )

      select * from bill_data inner join (select max(b_createddate) as maxcreateddate, bd_consumercode from bill_data group by bd_consumercode) as max ON max.maxcreateddate=b_createddate
   searchParams: 
    condition: AND
    params:
    - name: b.tenantid
      isMandatory: true
      jsonPath: $.searchCriteria.tenantId
    - name: bd.consumercode
      isMandatory: false
      jsonPath: $.searchCriteria.consumerCode
    - name: bd.businessservice
      isMandatory: false
      jsonPath: $.searchCriteria.businesService
    - name: b.mobilenumber
      isMandatory: false
      jsonPath: $.searchCriteria.mobileNumber
    - name: bd.billno
      isMandatory: false
      jsonPath: $.searchCriteria.billNo
    - name: ptadd.locality
      isMandatory: false
      jsonPath: $.searchCriteria.locality
    - name: ptdet.financialyear
      isMandatory: false
      jsonPath: $.searchCriteria.financialYear
    - name: fromperiod
      isMandatory: false
      jsonPath: $.searchCriteria.fromPeriod
      operator: LE
    - name: toperiod
      isMandatory: false
      jsonPath: $.searchCriteria.toPeriod
      operator: GE
    - name: b.status
      isMandatory: false
      jsonPath: $.searchCriteria.billActive

   output:
    jsonFormat: {"ResponseInfo": {},"Bills": []}
    outJsonPath: $.Bills
    responseInfoPath: $.ResponseInfo
    

 - name: waterbills
   isCustomerRowMapEnabled: true
   rowMapperKey: billsearch
   query: 
    baseQuery:   with bill_data as ( 
            SELECT b.id AS b_id, b.mobilenumber, 
            b.tenantid AS b_tenantid, b.payername AS b_payername, 
            b.payeraddress AS b_payeraddress, b.payeremail AS b_payeremail, 
            b.isactive AS b_isactive, b.iscancelled AS b_iscancelled, 
            b.createdby AS b_createdby, b.status as b_status, b.filestoreid AS b_filestoreid,
            b.createddate AS b_createddate, b.lastmodifiedby AS b_lastmodifiedby, 
            b.lastmodifieddate AS b_lastmodifieddate, bd.id AS bd_id, 
            bd.billid AS bd_billid, bd.tenantid AS bd_tenantid,
            bd.businessservice AS bd_businessservice, bd.demandid, 
            bd.fromperiod, bd.toperiod, 
            bd.billno AS bd_billno, bd.billdate AS bd_billdate, 
            bd.consumercode AS bd_consumercode, bd.consumertype AS bd_consumertype, 
            bd.billdescription AS bd_billdescription, bd.displaymessage AS bd_displaymessage, 
            bd.minimumamount AS bd_minimumamount, bd.totalamount AS bd_totalamount, 
            bd.callbackforapportioning AS bd_callbackforapportioning, bd.expirydate AS bd_expirydate, 
            bd.partpaymentallowed AS bd_partpaymentallowed, bd.isadvanceallowed as bd_isadvanceallowed, 
            bd.collectionmodesnotallowed AS bd_collectionmodesnotallowed, bd.createddate as bd_createddate, 
            b.additionaldetails as b_additionaldetails,  bd.additionaldetails as bd_additionaldetails,
            ad.id AS ad_id, ad.tenantid AS ad_tenantid, 
            ad.billdetail AS ad_billdetail, ad.glcode AS ad_glcode, 
            ad.orderno AS ad_orderno, ad.accountdescription AS ad_accountdescription, 
            ad.amount AS ad_amount, ad.adjustedamount AS ad_adjustedamount, 
            ad.taxheadcode AS ad_taxheadcode, ad.demanddetailid, 
            ad.isactualdemand AS ad_isactualdemand, ad.purpose AS ad_purpose,   
            ad.additionaldetails as ad_additionaldetails,
            ptadd.doorNo as ptadd_doorNo, ptadd.landmark as ptadd_landmark, 
            ptadd.city as ptadd_city, ptadd.pincode as ptadd_pincode, 
            ptadd.locality as ptadd_locality, ptown.userid as ptown_userid 

           FROM egbs_bill_v1 b INNER JOIN egbs_billdetail_v1 bd ON b.id = bd.billid AND b.tenantid = bd.tenantid 
            INNER JOIN egbs_billaccountdetail_v1 ad ON bd.id = ad.billdetail AND bd.tenantid = ad.tenantid
            INNER JOIN eg_ws_connection conn ON bd.consumercode = conn.connectionno
            INNER JOIN eg_pt_property pt ON conn.property_id = pt.id
            INNER JOIN eg_pt_address ptadd ON ptadd.propertyid = pt.id 
            INNER JOIN eg_pt_owner ptown ON ptown.propertyid = pt.id $where )

      select * from bill_data inner join (select max(b_createddate) as maxcreateddate, bd_consumercode from bill_data group by bd_consumercode) as max ON max.maxcreateddate=b_createddate
   searchParams: 
    condition: AND
    params:
    - name: b.tenantid
      isMandatory: true
      jsonPath: $.searchCriteria.tenantId
    - name: bd.consumercode
      isMandatory: false
      jsonPath: $.searchCriteria.consumerCode
    - name: bd.businessservice
      isMandatory: false
      jsonPath: $.searchCriteria.businesService
    - name: b.mobilenumber
      isMandatory: false
      jsonPath: $.searchCriteria.mobileNumber
    - name: bd.billno
      isMandatory: false
      jsonPath: $.searchCriteria.billNo
    - name: ptadd.locality
      isMandatory: false
      jsonPath: $.searchCriteria.locality
    - name: fromperiod
      isMandatory: false
      jsonPath: $.searchCriteria.fromPeriod
      operator: LE
    - name: toperiod
      isMandatory: false
      jsonPath: $.searchCriteria.toPeriod
      operator: GE
    - name: b.status
      isMandatory: false
      jsonPath: $.searchCriteria.billActive

   output:
    jsonFormat: {"ResponseInfo": {},"Bills": []}
    outJsonPath: $.Bills
    responseInfoPath: $.ResponseInfo




 - name: seweragebills
   isCustomerRowMapEnabled: true
   rowMapperKey: billsearch
   query: 
    baseQuery:   with bill_data as ( 
            SELECT b.id AS b_id, b.mobilenumber, 
            b.tenantid AS b_tenantid, b.payername AS b_payername, 
            b.payeraddress AS b_payeraddress, b.payeremail AS b_payeremail, 
            b.isactive AS b_isactive, b.iscancelled AS b_iscancelled, 
            b.createdby AS b_createdby, b.status as b_status, b.filestoreid AS b_filestoreid,
            b.createddate AS b_createddate, b.lastmodifiedby AS b_lastmodifiedby, 
            b.lastmodifieddate AS b_lastmodifieddate, bd.id AS bd_id, 
            bd.billid AS bd_billid, bd.tenantid AS bd_tenantid,
            bd.businessservice AS bd_businessservice, bd.demandid, 
            bd.fromperiod, bd.toperiod, 
            bd.billno AS bd_billno, bd.billdate AS bd_billdate, 
            bd.consumercode AS bd_consumercode, bd.consumertype AS bd_consumertype, 
            bd.billdescription AS bd_billdescription, bd.displaymessage AS bd_displaymessage, 
            bd.minimumamount AS bd_minimumamount, bd.totalamount AS bd_totalamount, 
            bd.callbackforapportioning AS bd_callbackforapportioning, bd.expirydate AS bd_expirydate, 
            bd.partpaymentallowed AS bd_partpaymentallowed, bd.isadvanceallowed as bd_isadvanceallowed, 
            bd.collectionmodesnotallowed AS bd_collectionmodesnotallowed, bd.createddate as bd_createddate, 
            b.additionaldetails as b_additionaldetails,  bd.additionaldetails as bd_additionaldetails,
            ad.id AS ad_id, ad.tenantid AS ad_tenantid, 
            ad.billdetail AS ad_billdetail, ad.glcode AS ad_glcode, 
            ad.orderno AS ad_orderno, ad.accountdescription AS ad_accountdescription, 
            ad.amount AS ad_amount, ad.adjustedamount AS ad_adjustedamount, 
            ad.taxheadcode AS ad_taxheadcode, ad.demanddetailid, 
            ad.isactualdemand AS ad_isactualdemand, ad.purpose AS ad_purpose,   
            ad.additionaldetails as ad_additionaldetails,
            ptadd.doorNo as ptadd_doorNo, ptadd.landmark as ptadd_landmark, 
            ptadd.city as ptadd_city, ptadd.pincode as ptadd_pincode, 
            ptadd.locality as ptadd_locality, ptown.userid as ptown_userid 

           FROM egbs_bill_v1 b INNER JOIN egbs_billdetail_v1 bd ON b.id = bd.billid AND b.tenantid = bd.tenantid 
            INNER JOIN egbs_billaccountdetail_v1 ad ON bd.id = ad.billdetail AND bd.tenantid = ad.tenantid
            INNER JOIN eg_sw_connection conn ON bd.consumercode = conn.connectionno
            INNER JOIN eg_pt_property pt ON conn.property_id = pt.id
            INNER JOIN eg_pt_address ptadd ON ptadd.propertyid = pt.id 
            INNER JOIN eg_pt_owner ptown ON ptown.propertyid = pt.id $where )

      select * from bill_data inner join (select max(b_createddate) as maxcreateddate, bd_consumercode from bill_data group by bd_consumercode) as max ON max.maxcreateddate=b_createddate
   searchParams: 
    condition: AND
    params:
    - name: b.tenantid
      isMandatory: true
      jsonPath: $.searchCriteria.tenantId
    - name: bd.consumercode
      isMandatory: false
      jsonPath: $.searchCriteria.consumerCode
    - name: bd.businessservice
      isMandatory: false
      jsonPath: $.searchCriteria.businesService
    - name: b.mobilenumber
      isMandatory: false
      jsonPath: $.searchCriteria.mobileNumber
    - name: bd.billno
      isMandatory: false
      jsonPath: $.searchCriteria.billNo
    - name: ptadd.locality
      isMandatory: false
      jsonPath: $.searchCriteria.locality
    - name: fromperiod
      isMandatory: false
      jsonPath: $.searchCriteria.fromPeriod
      operator: LE
    - name: toperiod
      isMandatory: false
      jsonPath: $.searchCriteria.toPeriod
      operator: GE
    - name: b.status
      isMandatory: false
      jsonPath: $.searchCriteria.billActive

   output:
    jsonFormat: {"ResponseInfo": {},"Bills": []}
    outJsonPath: $.Bills
    responseInfoPath: $.ResponseInfo
