ServiceMaps:
 serviceName: Property Tax - rainmaker
 version: 1.0.0
 mappings:
  - topic: save-pgr-request
    configKey: INDEX
    indexes:
      - name: pgr-services
        type: general
        id: $.service.serviceRequestId
        jsonPath: $.PGREntity
        timeStampField: $.service.auditDetails.lastModifiedTime
        fieldsToBeMasked: ["$.service.citizen.userName", "$.service.citizen.name", "$.service.citizen.mobileNumber", "$.service.citizen.emailId"]
        customJsonMapping:
          indexMapping: {"Data":{"PGREntity":{},"ward":{},"tenantData":{}, "history":{}}}
          fieldMapping:
          - inJsonPath: $
            outJsonPath: $.Data.PGREntity
          externalUriMapping:
          - path: http://egov-location.egov:8080/egov-location/location/v11/boundarys/_search
            queryParam: hierarchyTypeCode=ADMIN,boundaryType=Locality,codes=$.service.address.locality.code,tenantId=$.service.tenantId
            apiRequest: {"RequestInfo":{"apiId":"org.egov.pt","ver":"1.0","ts":1502890899493,"action":"asd","did":"4354648646","key":"xyz","msgId":"654654","requesterId":"61","authToken":"d9994555-7656-4a67-ab3a-a952a0d4dfc8","userInfo":{"id":1,"uuid":"1fec8102-0e02-4d0a-b283-cd80d5dab067","type":"EMPLOYEE","tenantId":"pb.amritsar","roles":[{"name":"Employee","code":"EMPLOYEE","tenantId":"pb.amritsar"}]}}}
            uriResponseMapping:
            - inJsonPath: $.TenantBoundary[0].boundary[0]
              outJsonPath: $.Data.ward
          - path: http://egov-workflow-v2.egov:8080/egov-workflow-v2/egov-wf/process/_search
            queryParam: businessIds=$.service.serviceRequestId,history=true,tenantId=$.service.tenantId
            apiRequest: {"RequestInfo":{"apiId":"org.egov.pt","ver":"1.0","ts":1502890899493,"action":"asd","did":"4354648646","key":"xyz","msgId":"654654","requesterId":"61","authToken":"d9994555-7656-4a67-ab3a-a952a0d4dfc8","userInfo":{"id":1,"uuid":"1fec8102-0e02-4d0a-b283-cd80d5dab067","type":"EMPLOYEE","tenantId":"pb.amritsar","roles":[{"name":"Employee","code":"EMPLOYEE","tenantId":"pb.amritsar"}]}}}
            uriResponseMapping:
            - inJsonPath: $.ProcessInstances
              outJsonPath: $.Data.history
          mdmsMapping:
          - path: http://egov-mdms-service.egov:8080/egov-mdms-service/v1/_search
            moduleName: tenant
            masterName: tenants
            tenantId: pb
            filter: "[?(@.code == $tenant)]"
            filterMapping:
            - variable: $tenant
              valueJsonpath: $.service.tenantId
            uriResponseMapping:
            - inJsonPath: $.MdmsRes.tenant.tenants
              outJsonPath: $.Data.tenantData
             
  - topic: update-pgr-request
    configKey: INDEX
    indexes:
      - name: pgr-services
        type: general
        id: $.service.serviceRequestId
        jsonPath: $.PGREntity
        timeStampField: $.service.auditDetails.lastModifiedTime
        fieldsToBeMasked: ["$.service.citizen.userName", "$.service.citizen.name", "$.service.citizen.mobileNumber", "$.service.citizen.emailId"]
        customJsonMapping:
          indexMapping: {"Data":{"PGREntity":{},"ward":{},"tenantData":{}, "history":{}}}
          fieldMapping:
          - inJsonPath: $
            outJsonPath: $.Data.PGREntity
          externalUriMapping:
          - path: http://egov-location.egov:8080/egov-location/location/v11/boundarys/_search
            queryParam: hierarchyTypeCode=ADMIN,boundaryType=locality,codes=$.service.address.locality.code,tenantId=$.service.tenantId
            apiRequest: {"RequestInfo":{"apiId":"org.egov.pt","ver":"1.0","ts":1502890899493,"action":"asd","did":"4354648646","key":"xyz","msgId":"654654","requesterId":"61","authToken":"d9994555-7656-4a67-ab3a-a952a0d4dfc8","userInfo":{"id":1,"uuid":"1fec8102-0e02-4d0a-b283-cd80d5dab067","type":"EMPLOYEE","tenantId":"pb.amritsar","roles":[{"name":"Employee","code":"EMPLOYEE","tenantId":"pb.amritsar"}]}}}
            uriResponseMapping:
            - inJsonPath: $.TenantBoundary[0].boundary[0]
              outJsonPath: $.Data.ward
          - path: http://egov-workflow-v2.egov:8080/egov-workflow-v2/egov-wf/process/_search
            queryParam: businessIds=$.service.serviceRequestId,history=true,tenantId=$.service.tenantId
            apiRequest: {"RequestInfo":{"apiId":"org.egov.pt","ver":"1.0","ts":1502890899493,"action":"asd","did":"4354648646","key":"xyz","msgId":"654654","requesterId":"61","authToken":"d9994555-7656-4a67-ab3a-a952a0d4dfc8","userInfo":{"id":1,"uuid":"1fec8102-0e02-4d0a-b283-cd80d5dab067","type":"EMPLOYEE","tenantId":"pb.amritsar","roles":[{"name":"Employee","code":"EMPLOYEE","tenantId":"pb.amritsar"}]}}}
            uriResponseMapping:
            - inJsonPath: $.ProcessInstances
              outJsonPath: $.Data.history
          mdmsMapping:
          - path: http://egov-mdms-service.egov:8080/egov-mdms-service/v1/_search
            moduleName: tenant
            masterName: tenants
            tenantId: pb
            filter: "[?(@.code == $tenant)]"
            filterMapping:
            - variable: $tenant
              valueJsonpath: $.service.tenantId
            uriResponseMapping:
            - inJsonPath: $.MdmsRes.tenant.tenants
              outJsonPath: $.Data.tenantData
     
  - topic: pgr-services-legacyIndex
    configKey: LEGACYINDEX
    indexes:
      - name: pgr-services
        type: general
        isBulk: true
        id: $.service.serviceRequestId
        jsonPath: $.PGREntities.*
        timeStampField: $.service.auditDetails.lastModifiedTime
        fieldsToBeMasked: ["$.service.citizen.userName", "$.service.citizen.name", "$.service.citizen.mobileNumber", "$.service.citizen.emailId"]
        customJsonMapping:
          indexMapping: {"Data":{"PGREntity":{},"ward":{},"tenantData":{}, "history":{}}}
          fieldMapping:
          - inJsonPath: $
            outJsonPath: $.Data.PGREntity
          externalUriMapping:
          - path: http://egov-location.egov:8080/egov-location/location/v11/boundarys/_search
            queryParam: hierarchyTypeCode=ADMIN,boundaryType=locality,codes=$.service.address.locality.code,tenantId=$.service.tenantId
            apiRequest: {"RequestInfo":{"apiId":"org.egov.pt","ver":"1.0","ts":1502890899493,"action":"asd","did":"4354648646","key":"xyz","msgId":"654654","requesterId":"61","authToken":"d9994555-7656-4a67-ab3a-a952a0d4dfc8","userInfo":{"id":1,"uuid":"1fec8102-0e02-4d0a-b283-cd80d5dab067","type":"EMPLOYEE","tenantId":"pb.amritsar","roles":[{"name":"Employee","code":"EMPLOYEE","tenantId":"pb.amritsar"}]}}}
            uriResponseMapping:
            - inJsonPath: $.TenantBoundary[0].boundary[0]
              outJsonPath: $.Data.ward
          - path: http://egov-workflow-v2.egov:8080/egov-workflow-v2/egov-wf/process/_search
            queryParam: businessIds=$.service.serviceRequestId,history=true,tenantId=$.service.tenantId
            apiRequest: {"RequestInfo":{"apiId":"org.egov.pt","ver":"1.0","ts":1502890899493,"action":"asd","did":"4354648646","key":"xyz","msgId":"654654","requesterId":"61","authToken":"d9994555-7656-4a67-ab3a-a952a0d4dfc8","userInfo":{"id":1,"uuid":"1fec8102-0e02-4d0a-b283-cd80d5dab067","type":"EMPLOYEE","tenantId":"pb.amritsar","roles":[{"name":"Employee","code":"EMPLOYEE","tenantId":"pb.amritsar"}]}}}
            uriResponseMapping:
            - inJsonPath: $.ProcessInstances
              outJsonPath: $.Data.history
          mdmsMapping:
          - path: http://egov-mdms-service.egov:8080/egov-mdms-service/v1/_search
            moduleName: tenant
            masterName: tenants
            tenantId: pb
            filter: "[?(@.code == $tenant)]"
            filterMapping:
            - variable: $tenant
              valueJsonpath: $.service.tenantId
            uriResponseMapping:
            - inJsonPath: $.MdmsRes.tenant.tenants
              outJsonPath: $.Data.tenantData
            
