ServiceMaps:
 serviceName: Water Service - rainmaker
 version: 1.0.0
 mappings:
  - topic: save-ws-connection
    configKey: INDEX
    indexes:
      - name: water-services
        type: general
        id: $.id,$.property.tenantId
        jsonPath: $.WaterConnection
        timeStampField: $.additionalDetails.appCreatedDate
        customJsonMapping:
          indexMapping: {"Data":{"workflow": {"state": {}, "action": "", "assignes": []},"ownersmobileNos":[],"applicationNo":"","applicationStatus":"","status":"","connectionNo":"","oldConnectionNo":"","plumberInfo":[],"roadType":"","roadCuttingArea":"","connectionExecutionDate":"","connectionCategory":"","connectionType":"","additionalDetails":{},"id":"","propertyId":"","rainWaterHarvesting":"","waterSource":"","tenantId":"","meterId":"","meterInstallationDate":"","proposedPipeSize":"","proposedTaps":"","pipeSize":"","noOfTaps":"","history":{}}}
          fieldMapping:
          - inJsonPath: $.applicationStatus.state
            outJsonPath: $.Data.workflow.state
          - inJsonPath: $.processInstance.action
            outJsonPath: $.Data.workflow.action
          - inJsonPath: $.processInstance.assignes.*.uuid
            outJsonPath: $.Data.workflow.assignes
          - inJsonPath: $.property.owners.*.mobileNumber
            outJsonPath: $.Data.ownersmobileNos
          - inJsonPath: $.applicationNo
            outJsonPath: $.Data.applicationNo
          - inJsonPath: $.applicationStatus
            outJsonPath: $.Data.applicationStatus
          - inJsonPath: $.status
            outJsonPath: $.Data.status
          - inJsonPath: $.connectionNo
            outJsonPath: $.Data.connectionNo
          - inJsonPath: $.oldConnectionNo
            outJsonPath: $.Data.oldConnectionNo
          - inJsonPath: $.plumberInfo
            outJsonPath: $.Data.plumberInfo
          - inJsonPath: $.roadType
            outJsonPath: $.Data.roadType
          - inJsonPath: $.roadCuttingArea
            outJsonPath: $.Data.roadCuttingArea
          - inJsonPath: $.connectionExecutionDate
            outJsonPath: $.Data.connectionExecutionDate
          - inJsonPath: $.connectionCategory
            outJsonPath: $.Data.connectionCategory
          - inJsonPath: $.connectionType
            outJsonPath: $.Data.connectionType
          - inJsonPath: $.additionalDetails
            outJsonPath: $.Data.additionalDetails
          - inJsonPath: $.id
            outJsonPath: $.Data.id
          - inJsonPath: $.property.propertyId
            outJsonPath: $.Data.propertyId
          - inJsonPath: $.rainWaterHarvesting
            outJsonPath: $.Data.rainWaterHarvesting
          - inJsonPath: $.waterSource
            outJsonPath: $.Data.waterSource
          - inJsonPath: $.property.tenantId
            outJsonPath: $.Data.tenantId
          - inJsonPath: $.meterId
            outJsonPath: $.Data.meterId
          - inJsonPath: $.meterInstallationDate
            outJsonPath: $.Data.meterInstallationDate
          - inJsonPath: $.proposedPipeSize
            outJsonPath: $.Data.proposedPipeSize
          - inJsonPath: $.proposedTaps
            outJsonPath: $.Data.proposedTaps
          - inJsonPath: $.pipeSize
            outJsonPath: $.Data.pipeSize
          - inJsonPath: $.noOfTaps
            outJsonPath: $.Data.noOfTaps
          externalUriMapping:
          - path: http://egov-workflow-v2.egov:8080/egov-workflow-v2/egov-wf/process/_search
            queryParam: businessIds=$.applicationNo,history=true,tenantId=$.property.tenantId
            apiRequest: {"RequestInfo":{"apiId":"org.egov.pt","ver":"1.0","ts":1502890899493,"action":"asd","did":"4354648646","key":"xyz","msgId":"654654","requesterId":"61","authToken":"d9994555-7656-4a67-ab3a-a952a0d4dfc8","userInfo":{"id":1,"uuid":"1fec8102-0e02-4d0a-b283-cd80d5dab067","type":"EMPLOYEE","tenantId":"pb.amritsar","roles":[{"name":"Employee","code":"EMPLOYEE","tenantId":"pb.amritsar"}]}}}
            uriResponseMapping:
            - inJsonPath: $.ProcessInstances
              outJsonPath: $.Data.history
     

  - topic: update-ws-connection
    configKey: INDEX
    indexes:
      - name: water-services
        type: general
        id: $.id,$.property.tenantId
        jsonPath: $.WaterConnection
        timeStampField: $.additionalDetails.appCreatedDate
        customJsonMapping:
          indexMapping: {"Data":{"workflow": {"state": {}, "action": "", "assignes": []},"ownersmobileNos":[],"applicationNo":"","applicationStatus":"","status":"","connectionNo":"","oldConnectionNo":"","plumberInfo":[],"roadType":"","roadCuttingArea":"","connectionExecutionDate":"","connectionCategory":"","connectionType":"","additionalDetails":{},"id":"","propertyId":"","rainWaterHarvesting":"","waterSource":"","tenantId":"","meterId":"","meterInstallationDate":"","proposedPipeSize":"","proposedTaps":"","pipeSize":"","noOfTaps":"","history":{}}}
          fieldMapping:
          - inJsonPath: $.applicationStatus.state
            outJsonPath: $.Data.workflow.state
          - inJsonPath: $.processInstance.action
            outJsonPath: $.Data.workflow.action
          - inJsonPath: $.processInstance.assignes.*.uuid
            outJsonPath: $.Data.workflow.assignes
          - inJsonPath: $.property.owners.*.mobileNumber
            outJsonPath: $.Data.ownersmobileNos
          - inJsonPath: $.applicationNo
            outJsonPath: $.Data.applicationNo
          - inJsonPath: $.applicationStatus
            outJsonPath: $.Data.applicationStatus
          - inJsonPath: $.status
            outJsonPath: $.Data.status
          - inJsonPath: $.connectionNo
            outJsonPath: $.Data.connectionNo
          - inJsonPath: $.oldConnectionNo
            outJsonPath: $.Data.oldConnectionNo
          - inJsonPath: $.plumberInfo
            outJsonPath: $.Data.plumberInfo
          - inJsonPath: $.roadType
            outJsonPath: $.Data.roadType
          - inJsonPath: $.roadCuttingArea
            outJsonPath: $.Data.roadCuttingArea
          - inJsonPath: $.connectionExecutionDate
            outJsonPath: $.Data.connectionExecutionDate
          - inJsonPath: $.connectionCategory
            outJsonPath: $.Data.connectionCategory
          - inJsonPath: $.connectionType
            outJsonPath: $.Data.connectionType
          - inJsonPath: $.additionalDetails
            outJsonPath: $.Data.additionalDetails
          - inJsonPath: $.id
            outJsonPath: $.Data.id
          - inJsonPath: $.property.propertyId
            outJsonPath: $.Data.propertyId
          - inJsonPath: $.rainWaterHarvesting
            outJsonPath: $.Data.rainWaterHarvesting
          - inJsonPath: $.waterSource
            outJsonPath: $.Data.waterSource
          - inJsonPath: $.property.tenantId
            outJsonPath: $.Data.tenantId
          - inJsonPath: $.meterId
            outJsonPath: $.Data.meterId
          - inJsonPath: $.meterInstallationDate
            outJsonPath: $.Data.meterInstallationDate
          - inJsonPath: $.proposedPipeSize
            outJsonPath: $.Data.proposedPipeSize
          - inJsonPath: $.proposedTaps
            outJsonPath: $.Data.proposedTaps
          - inJsonPath: $.pipeSize
            outJsonPath: $.Data.pipeSize
          - inJsonPath: $.noOfTaps
            outJsonPath: $.Data.noOfTaps
          externalUriMapping:
          - path: http://egov-workflow-v2.egov:8080/egov-workflow-v2/egov-wf/process/_search
            queryParam: businessIds=$.applicationNo,history=true,tenantId=$.property.tenantId
            apiRequest: {"RequestInfo":{"apiId":"org.egov.pt","ver":"1.0","ts":1502890899493,"action":"asd","did":"4354648646","key":"xyz","msgId":"654654","requesterId":"61","authToken":"d9994555-7656-4a67-ab3a-a952a0d4dfc8","userInfo":{"id":1,"uuid":"1fec8102-0e02-4d0a-b283-cd80d5dab067","type":"EMPLOYEE","tenantId":"pb.amritsar","roles":[{"name":"Employee","code":"EMPLOYEE","tenantId":"pb.amritsar"}]}}}
            uriResponseMapping:
            - inJsonPath: $.ProcessInstances
              outJsonPath: $.Data.history
              
  - topic: update-ws-workflow
    configKey: INDEX
    indexes:
      - name: water-services
        type: general
        id: $.id,$.property.tenantId
        jsonPath: $.WaterConnection
        timeStampField: $.additionalDetails.appCreatedDate
        customJsonMapping:
          indexMapping: {"Data":{"workflow": {"state": {}, "action": "", "assignes": []},"ownersmobileNos":[],"applicationNo":"","applicationStatus":"","status":"","connectionNo":"","oldConnectionNo":"","plumberInfo":[],"roadType":"","roadCuttingArea":"","connectionExecutionDate":"","connectionCategory":"","connectionType":"","additionalDetails":{},"id":"","propertyId":"","rainWaterHarvesting":"","waterSource":"","tenantId":"","meterId":"","meterInstallationDate":"","proposedPipeSize":"","proposedTaps":"","pipeSize":"","noOfTaps":"","history":{}}}
          fieldMapping:
          - inJsonPath: $.applicationStatus.state
            outJsonPath: $.Data.workflow.state
          - inJsonPath: $.processInstance.action
            outJsonPath: $.Data.workflow.action
          - inJsonPath: $.processInstance.assignes.*.uuid
            outJsonPath: $.Data.workflow.assignes
          - inJsonPath: $.property.owners.*.mobileNumber
            outJsonPath: $.Data.ownersmobileNos
          - inJsonPath: $.applicationNo
            outJsonPath: $.Data.applicationNo
          - inJsonPath: $.applicationStatus
            outJsonPath: $.Data.applicationStatus
          - inJsonPath: $.status
            outJsonPath: $.Data.status
          - inJsonPath: $.connectionNo
            outJsonPath: $.Data.connectionNo
          - inJsonPath: $.oldConnectionNo
            outJsonPath: $.Data.oldConnectionNo
          - inJsonPath: $.plumberInfo
            outJsonPath: $.Data.plumberInfo
          - inJsonPath: $.roadType
            outJsonPath: $.Data.roadType
          - inJsonPath: $.roadCuttingArea
            outJsonPath: $.Data.roadCuttingArea
          - inJsonPath: $.connectionExecutionDate
            outJsonPath: $.Data.connectionExecutionDate
          - inJsonPath: $.connectionCategory
            outJsonPath: $.Data.connectionCategory
          - inJsonPath: $.connectionType
            outJsonPath: $.Data.connectionType
          - inJsonPath: $.additionalDetails
            outJsonPath: $.Data.additionalDetails
          - inJsonPath: $.id
            outJsonPath: $.Data.id
          - inJsonPath: $.property.propertyId
            outJsonPath: $.Data.propertyId
          - inJsonPath: $.rainWaterHarvesting
            outJsonPath: $.Data.rainWaterHarvesting
          - inJsonPath: $.waterSource
            outJsonPath: $.Data.waterSource
          - inJsonPath: $.property.tenantId
            outJsonPath: $.Data.tenantId
          - inJsonPath: $.meterId
            outJsonPath: $.Data.meterId
          - inJsonPath: $.meterInstallationDate
            outJsonPath: $.Data.meterInstallationDate
          - inJsonPath: $.proposedPipeSize
            outJsonPath: $.Data.proposedPipeSize
          - inJsonPath: $.proposedTaps
            outJsonPath: $.Data.proposedTaps
          - inJsonPath: $.pipeSize
            outJsonPath: $.Data.pipeSize
          - inJsonPath: $.noOfTaps
            outJsonPath: $.Data.noOfTaps
          externalUriMapping:
          - path: http://egov-workflow-v2.egov:8080/egov-workflow-v2/egov-wf/process/_search
            queryParam: businessIds=$.applicationNo,history=true,tenantId=$.property.tenantId
            apiRequest: {"RequestInfo":{"apiId":"org.egov.pt","ver":"1.0","ts":1502890899493,"action":"asd","did":"4354648646","key":"xyz","msgId":"654654","requesterId":"61","authToken":"d9994555-7656-4a67-ab3a-a952a0d4dfc8","userInfo":{"id":1,"uuid":"1fec8102-0e02-4d0a-b283-cd80d5dab067","type":"EMPLOYEE","tenantId":"pb.amritsar","roles":[{"name":"Employee","code":"EMPLOYEE","tenantId":"pb.amritsar"}]}}}
            uriResponseMapping:
            - inJsonPath: $.ProcessInstances
              outJsonPath: $.Data.history
